import ProjectDescription

// Tuist configuration for MayAyeEyeDen.
//
// This is the `Tuist.swift` manifest (Tuist looks for it as `Tuist/Config.swift`
// or `Tuist.swift` at the root — both are equivalent). It controls generation
// behaviour shared across the workspace.
//
// Mirrors the scheme layout produced by the old `project.yml` (XcodeGen), where
// each target gets exactly one scheme. We keep Tuist's automatic per-target
// (project-level) scheme generation enabled, and disable the *extra* autogenerated
// workspace schemes so the generated workspace exposes only the two schemes CI
// builds against: `MayAyeEyeDen` and `MayAyeEyeDen-iOS`.
let tuist = Config(
    project: .tuist(
        generationOptions: .options(
            autogeneratedWorkspaceSchemes: .disabled
        )
    )
)
